"""Agregar registro de aperturas de puestos

Revision ID: 3707c18c5524
Revises: a5356c77ef65
Create Date: 2026-09-05 21:16:41.221219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3707c18c5524'
down_revision = 'a5356c77ef65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_posting_view',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_posting_id', sa.Integer(), nullable=False),
    sa.Column('viewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_posting_id'], ['job_posting.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_posting_view', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_posting_view_viewed_at'), ['viewed_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_posting_view', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_posting_view_viewed_at'))

    op.drop_table('job_posting_view')
    # ### end Alembic commands ###
