"""Agregar tipos de pregunta, opciones y respuestas con archivo

Revision ID: 8c3c96d4ac97
Revises: 3707c18c5524
Create Date: 2026-09-05 21:21:32.696951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c3c96d4ac97'
down_revision = '3707c18c5524'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_option',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=255), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selected_option_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('answer_file_path', sa.String(length=255), nullable=True))
        batch_op.create_foreign_key(None, 'question_option', ['selected_option_id'], ['id'])

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question_type', sa.String(length=20), nullable=False, server_default='text'))
        batch_op.alter_column('question_type', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_column('question_type')

    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('answer_file_path')
        batch_op.drop_column('selected_option_id')

    op.drop_table('question_option')
    # ### end Alembic commands ###
