"""Agregar resumen psicologico de IA

Revision ID: ba84fa587e40
Revises: 3ef38605e21f
Create Date: 2026-09-05 21:37:01.330854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba84fa587e40'
down_revision = '3ef38605e21f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_psychological_summary', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.drop_column('ai_psychological_summary')

    # ### end Alembic commands ###
